=== RimonAdel/DBMS-JDBC/JDBC/Proect 3/Directory/data.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
<xs:element name="table">
<xs:complexType>
<xs:sequence>
<xs:element name="Element" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="name" type="xs:string"/>
<xs:element name="surname" type="xs:string"/>
<xs:element name="id" type="xs:int"/>
<xs:element name="gpa" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== RimonAdel/DBMS-JDBC/JDBC/Proect 3/Directory/data.xml
<?ignore name,string,surname,string,id,int,gpa,string ?>
<table
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com data.xsd"><Element>
<name>
mark
</name>
<surname>
maurice
</surname>
<id>
3791
</id>
<gpa>
3.6
</gpa>
</Element><Element>
<name>
salma
</name>
<surname>
tharwat
</surname>
<id>
2134
</id>
<gpa>
3.9
</gpa>
</Element><Element>
<name>
marian
</name>
<surname>
shaker
</surname>
<id>
4358
</id>
<gpa>
4
</gpa>
</Element><Element>
<name>
rimon
</name>
<surname>
adel
</surname>
<id>
4441
</id>
<gpa>
3.8
</gpa>
</Element><Element>
<name>
omar
</name>
<surname>
elsherif
</surname>
<id>
2145
</id>
<gpa>
3.8
</gpa>
</Element><Element>
<name>
amr
</name>
<surname>
ramadan
</surname>
<id>
8886
</id>
<gpa>
3.7
</gpa>
</Element><Element>
<name>
amr
</name>
<surname>
mostafa
</surname>
<id>
7925
</id>
<gpa>
3
</gpa>
</Element><Element>
<name>
rimon
</name>
<surname>
wadia
</surname>
<id>
4442
</id>
<gpa>
3.5
</gpa>
</Element><Element>
<name>
andrew
</name>
<surname>
wadia
</surname>
<id>
7998
</id>
<gpa>
2.5
</gpa>
</Element><Element>
<name>
ahmed
</name>
<surname>
ahmed
</surname>
<id>
3228
</id>
<gpa>
2.9
</gpa>
</Element>
</table>
